(function(){
      // 同期URLチェック
        var h=location.hash;
          if(h.indexOf('#sync=')===0){
              try{
                    var d=JSON.parse(decodeURIComponent(atob(h.slice(6))));
                          if(Array.isArray(d)&&confirm(d.length+'件のメモを同期しますか?\n現在のデータは上書きされます')){
                                  localStorage.setItem('med_main',JSON.stringify(d));
                                          history.replaceState(null,'',location.pathname);
                                                  location.reload();
                                                        }else history.replaceState(null,'',location.pathname);
                                                            }catch(e){history.replaceState(null,'',location.pathname);}
                                                              }

                                                                // 同期UI追加
                                                                  function addSyncUI(){
                                                                      var s=document.createElement('style');
                                                                          s.textContent=
                                                                                '.sfab{position:fixed;bottom:76px;right:16px;z-index:9999;width:48px;height:48px;'+
                                                                                      'border-radius:50%;background:#1d4ed8;border:2px solid #3b82f6;color:#fff;'+
                                                                                            'font-size:22px;cursor:pointer;display:flex;align-items:center;justify-content:center;'+
                                                                                                  'box-shadow:0 2px 12px rgba(0,0,0,.5);transition:.2s}'+
                                                                                                        '.sfab:hover{background:#2563eb;transform:scale(1.1)}'+
                                                                                                              '.sp{position:fixed;bottom:132px;right:16px;z-index:9999;background:#0f1b35;'+
                                                                                                                    'border:1px solid #2d4a8a;border-radius:14px;padding:14px;width:200px;'+
                                                                                                                          'box-shadow:0 8px 32px rgba(0,0,0,.5);display:none}'+
                                                                                                                                '.sp.o{display:block}'+
                                                                                                                                      '.sp h4{margin:0 0 8px;color:#93c5fd;font-size:11px;text-transform:uppercase}'+
                                                                                                                                            '.sp button{display:block;width:100%;margin:4px 0;padding:8px 12px;'+
                                                                                                                                                  'background:#1e3a6e;border:1px solid #2d5aa0;color:#e2e8f0;border-radius:8px;'+
                                                                                                                                                        'cursor:pointer;font-size:13px;text-align:left;transition:.15s}'+
                                                                                                                                                              '.sp button:hover{background:#254d94;color:#fff}';
                                                                                                                                                                  document.head.appendChild(s);

                                                                                                                                                                      var f=document.createElement('button');
                                                                                                                                                                          f.className='sfab';f.innerHTML='🔄';f.title='データ同期';

                                                                                                                                                                              var p=document.createElement('div');
                                                                                                                                                                                  p.className='sp';
                                                                                                                                                                                      p.innerHTML='<h4>📱 デバイス間同期</h4>';

                                                                                                                                                                                          function btn(t,fn){
                                                                                                                                                                                                var b=document.createElement('button');
                                                                                                                                                                                                      b.textContent=t;b.onclick=fn;p.appendChild(b);
                                                                                                                                                                                                          }

                                                                                                                                                                                                              btn('📋 同期URLをコピー',function(){
                                                                                                                                                                                                                    try{
                                                                                                                                                                                                                            var enc=btoa(encodeURIComponent(localStorage.getItem('med_main')||'[]'));
                                                                                                                                                                                                                                    var url=location.origin+location.pathname+'#sync='+enc;
                                                                                                                                                                                                                                            navigator.clipboard.writeText(url).then(function(){
                                                                                                                                                                                                                                                      alert('✅ コピーしました!\nスマホのブラウザに貼り付けて開くとメモが同期されます');
                                                                                                                                                                                                                                                              }).catch(function(){prompt('URLをスマホで開いてください:',url);});
                                                                                                                                                                                                                                                                    }catch(e){}
                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                            btn('⬇️ JSONエクスポート',function(){
                                                                                                                                                                                                                                                                                  var blob=new Blob([localStorage.getItem('med_main')||'[]'],{type:'application/json'});
                                                                                                                                                                                                                                                                                        var a=document.createElement('a');
                                                                                                                                                                                                                                                                                              a.href=URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                                    a.download='memo-'+(new Date().toISOString().slice(0,10))+'.json';
                                                                                                                                                                                                                                                                                                          a.click();URL.revokeObjectURL(a.href);
                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                  btn('⬆️ JSONインポート',function(){
                                                                                                                                                                                                                                                                                                                        var i=document.createElement('input');
                                                                                                                                                                                                                                                                                                                              i.type='file';i.accept='.json';
                                                                                                                                                                                                                                                                                                                                    i.onchange=function(e){
                                                                                                                                                                                                                                                                                                                                            var fi=e.target.files[0];if(!fi)return;
                                                                                                                                                                                                                                                                                                                                                    var r=new FileReader();
                                                                                                                                                                                                                                                                                                                                                            r.onload=function(ev){
                                                                                                                                                                                                                                                                                                                                                                      try{
                                                                                                                                                                                                                                                                                                                                                                                  var d=JSON.parse(ev.target.result);
                                                                                                                                                                                                                                                                                                                                                                                              if(Array.isArray(d)&&confirm(d.length+'件読み込みます。現在のデータは上書きされます')){
                                                                                                                                                                                                                                                                                                                                                                                                            localStorage.setItem('med_main',JSON.stringify(d));
                                                                                                                                                                                                                                                                                                                                                                                                                          location.reload();
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }catch(e){alert('ファイルが正しくありません');}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        };r.readAsText(fi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };i.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      f.onclick=function(e){e.stopPropagation();p.classList.toggle('o');};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.addEventListener('click',function(e){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(!f.contains(e.target)&&!p.contains(e.target))p.classList.remove('o');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.body.appendChild(f);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.body.appendChild(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(document.readyState==='loading')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener('DOMContentLoaded',addSyncUI);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else addSyncUI();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();
})